version: '3'

services:

  webmvc:
    image: web 
    build:
      context: ./web
      dockerfile: Dockerfile.debug
    ports: 
    - "8080:80"
    volumes: 
      - ./web/bin/pub/:/app
    container_name: web
    depends_on:
      - applicants.api
      - identity.api
      - jobs.api

  applicants.api:
    image: applicants.api
    environment:
      - ConnectionString=Initial Catalog=dotnetgigs.applicants;Data Source=.;Integrated Security=SSPI;
    build:
      context: ./services/applicants.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8081:80"
    volumes: 
      - ./services/applicants.api/bin/pub/:/app
    container_name: applicants.api
    depends_on:
      - sql.data
      - rabbitmq

  jobs.api:
    image: jobs.api
    environment:
      - ConnectionString=Initial Catalog=dotnetgigs.applicants;Data Source=.;Integrated Security=SSPI;   
    build:
      context: ./services/jobs.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8083:80"
    volumes: 
      - ./services/jobs.api/bin/pub/:/app
    container_name: jobs.api
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: identity.api
    environment:
      - RedisHost=127.0.0.1:6379
    build:
      context: ./services/identity.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8084:80"
    volumes: 
      - ./services/identity.api/bin/pub/:/app
    container_name: identity.api
    depends_on:
      - user.data       

  sql.data:
    image: mssql-linux
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "5433:1433"
    container_name: mssql-linux

  user.data:
    image: redis  

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    container_name: rabbitmq
  

   
 